name: Sync to 2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Askpass
      run: |
        cat > ~/.git-askpass <<EOF
        #!/bin/sh
        echo "$PAT"
        EOF
        chmod +x ~/.git-askpass
      env:
        PAT: ${{ secrets.PAT }}

    - name: Push to luckygametools2.github.io
      env:
        GIT_ASKPASS: ~/.git-askpass
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

        git remote add target https://github.com/luckygametools/luckygametools2.github.io.git
        git push target HEAD:main --force
