name: Sync to 2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Git Credentials
      run: |
        cat > ~/.git-askpass <<EOF
        echo ${PAT}
        EOF
        chmod +x ~/.git-askpass
      env:
        PAT: ${{ secrets.PAT }}

    - name: Push to luckygametools2.github.io
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git config --global core.askPass "~/.git-askpass"

        git remote add target https://github.com/luckygametools/luckygametools2.github.io.git
        git push target HEAD:main --force
